### ISSUE TITLE
I have a similar project - want to join forces?

### ISSUE THREAD

**Issue by mikefarah** [030/go-yq#41]
Hey just saw your post on jq, I also have a go implementation:

https://github.com/mikefarah/yq

I have a bunch of outstanding things to do - not sure if you're interested in helping out!

If not - no worries

**Comment by 030** [comment]
@mikefarah Could idea. I have just ran your tool and it seems to work well:

```
~/Downloads/yq_windows_amd64.exe read defaults/main.yml firefox_version
```

Perhaps you could add me as a contributor. If true, then I will add a deprecation note to my repository and refer to yours. Perhaps you could have a look to the libraries and code in this repository whether these could be useful for yours as well. Perhaps you could assign a first good issue to me.

**Comment by 030** [comment]
@mikefarah I added a note to the README (see commit related to this issue) and created multiple issues in your project.

**Comment by mikefarah** [comment]
Cool - there are heaps of feature requests on yq, I have them labelled as 'enhancement' - feel free to browse:

This would be neat (but might be a tad tricky):
https://github.com/mikefarah/yq/issues/173

The matchesKey function in data-navigator would need to be update to also pass in the value at the location, then we could attempt to match the value expression in the key to the value object.

Otherwise feel free to browse issues and pick one of your fancy.
